[Assets.PropStatic]
objects = """
/Projects/dsready_content/nv_content/common_assets/props_general/bucket_01_dam/bucket_01_dam.usd
/Projects/dsready_content/nv_content/common_assets/props_general/brick_01_pile/brick_01_pile.usd
/Projects/dsready_content/nv_content/common_assets/props_general/asphalt_chunk_01/asphalt_chunk_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/bagged_groceries_01/bagged_groceries_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/box_cardboard_dam_02/box_cardboard_dam_02.usd
/Projects/dsready_content/nv_content/common_assets/props_general/box_cardboard_dam_03/box_cardboard_dam_03.usd
/Projects/dsready_content/nv_content/common_assets/props_general/box_cardboard_dirty_02/box_cardboard_dirty_02.usd
/Projects/dsready_content/nv_content/common_assets/props_general/box_cardboard_dirty_03/box_cardboard_dirty_03.usd
/Projects/dsready_content/nv_content/common_assets/props_general/box_cardboard_old_01/box_cardboard_old_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/car_dam_pieces/car_dam_pieces.usd
/Projects/dsready_content/nv_content/common_assets/props_general/chair_camping_01_dam/chair_camping_01_dam.usd
/Projects/dsready_content/nv_content/common_assets/props_general/chair_folding_dam_01/chair_folding_dam_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/chair_folding_outdoor_01_dam/chair_folding_outdoor_01_dam.usd
/Projects/dsready_content/nv_content/common_assets/props_general/chair_folding_outdoor_01_dirty/chair_folding_outdoor_01_dirty.usd
/Projects/dsready_content/nv_content/common_assets/props_general/chair_office_wheeled_01_dam/chair_office_wheeled_01_dam.usd
/Projects/dsready_content/nv_content/common_assets/props_general/chair_office_01/chair_office_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/concrete_bollard_dirt_pile_01/concrete_bollard_dirt_pile_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/crate_dam_02_dirty/crate_dam_02_dirty.usd
/Projects/dsready_content/nv_content/common_assets/props_general/crate_dam_02/crate_dam_02.usd
/Projects/dsready_content/nv_content/common_assets/props_general/crate_dam_01/crate_dam_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/crate_dirty_01/crate_dirty_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/desk_office_dam_01/desk_office_dam_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/luggage_soft_dam_01/luggage_soft_dam_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/palette_rackable_01_dirty/palette_rackable_01_dirty.usd
/Projects/dsready_content/nv_content/common_assets/props_general/pallet_02_dam/pallet_02_dam.usd
/Projects/dsready_content/nv_content/common_assets/props_general/pallet_02_dirty/pallet_02_dirty.usd
/Projects/dsready_content/nv_content/common_assets/props_general/outdoor_table_mod_a_01/outdoor_table_mod_a_01_chair.usd
/Projects/dsready_content/nv_content/common_assets/props_general/pallet_dam_01/pallet_dam_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/pallet_dirty_01/pallet_dirty_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/pebble_dirt/pebble_dirt.usd
/Projects/dsready_content/nv_content/common_assets/props_general/pebble_dirt_gravel_01/pebble_dirt_gravel_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/pile_dirt_small_01/pile_dirt_small_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/pile_dirt_large_01/pile_dirt_large_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/plant_potted_dam_01/plant_potted_dam_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/rock_02/rock_02.usd
/Projects/dsready_content/nv_content/common_assets/props_general/rock_03_broken/rock_03_broken.usd
/Projects/dsready_content/nv_content/common_assets/props_general/rocks_fallen_large_01/rocks_fallen_large_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/rocks_fallen_large_02/rocks_fallen_large_02.usd
/Projects/dsready_content/nv_content/common_assets/props_general/rocks_fallen_med_01/rocks_fallen_med_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/rocks_fallen_med_02/rocks_fallen_med_02.usd
/Projects/dsready_content/nv_content/common_assets/props_general/rocks_fallen_pile_01/rocks_fallen_pile_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/rocks_fallen_pile_03/rocks_fallen_pile_03.usd
/Projects/dsready_content/nv_content/common_assets/props_general/rocks_fallen_small_01/rocks_fallen_small_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/rocks_fallen_small_02/rocks_fallen_small_02.usd
/Projects/dsready_content/nv_content/common_assets/props_general/tire_lost_vehicle_dam_01/tire_lost_vehicle_dam_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/wheel_lost_vehicle_01/wheel_lost_vehicle_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/wheel_w_tire_lost_vehicle_01/wheel_w_tire_lost_vehicle_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/toolbox_dam_01/toolbox_dam_01.usd
/Projects/dsready_content/nv_content/common_assets/props_general/tree_trunk_01/tree_trunk_01.usd
"""