[Assets.PropStatic]
objects = """
/Projects/dsready_content/nv_content/common_assets/props_traffic/barrier_jersey_set_a/barrier_jersey.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/barrier_traffic_waterfilled_01/barrier_traffic_waterfilled_01.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/barrier_traffic_waterfilled_02/barrier_traffic_waterfilled_02.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/barrier_traffic_waterfilled_03/barrier_traffic_waterfilled_03.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/barrier_traffic_waterfilled_04/barrier_traffic_waterfilled_04.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/barrier_waterfilled_05/barrier_waterfilled_05.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/bollard_01/bollard_01.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/bollard_chain_1pt8m/bollard_chain_1pt8m.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/bollard_chain_3pt6m/bollard_chain_3pt6m.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/bollard_high/bollard_high.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/bollard_low/bollard_low.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/cone_safety_01_18_inch_dam/cone_safety_01_18_inch_dam.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/cone_safety_01_28_inch_dam/cone_safety_01_28_inch_dam.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/cone_safety_01_36_inch_dam/cone_safety_01_36_inch_dam.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/cone_safety_02_18_inch_dam/cone_safety_02_18_inch_dam.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/cone_safety_02_36_inch_dam/cone_safety_02_36_inch_dam.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/delineator_eur_01/delineator_eur_01.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/delineator_reflector/delineator_reflector.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/parkingblock_a3_01/parkingblock_a3_01_blue.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/parkingblock_a3_01/parkingblock_a3_01.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/parkingblock_a3_02/parkingblock_a3_02.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/parkingblock_a3_03/parkingblock_a3_03.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/road_reflector_01/road_reflector_01.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/road_reflector_04/road_reflector_04.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/roadbarrel_dam_01/roadbarrel_dam_01.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/roadbarrel_dam_02/roadbarrel_dam_02.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/roadbarrel_dam_03/roadbarrel_dam_03.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/safety_triangle_01/safety_triangle_01.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/safety_triangle_02/safety_triangle_02.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/sign_stripe_01/sign_stripe_01.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/speed_bump_01/speed_bump_01.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/speed_cushion_01/speed_cushion_01.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/traffic_cone_chn_red/traffic_cone_chn_red.usd
/Projects/dsready_content/nv_content/common_assets/props_traffic/traffic_cone_chn_yellow/traffic_cone_chn_yellow.usd
"""