[Sensors_Preview]
camera_front_wide_120fov = true

[Assets]
root = "{/app/drivesim/defaultNucleusRoot}/"
sets = [
    "ego.toml",
    "static_traffic_vehicles.toml",
    "static_public_vehicles.toml",
    "props_ncap.toml",
]

[Events.config]
enable_script = true
enable_periodic = true
periodic_start_frame = 0
collisions_enabled = true
enable_ego_teleportation = true

[[Events.setup]]
type='EgoRand'
func='setup'
pop_name='ego'
asset_file='ego.toml'
asset_sel_type='index'
asset_sel=[0]

[[Events.setup]]
type='WorldRand.weather'
func='setup'

[[Events.setup]]
type='PropStatic'
func='setup'
pop_name='my_props'
asset_file='props_ncap.toml' 
asset_sel_type='index'
asset_sel=[0,1,2,3,4]
asset_qty=1

[[Events.setup]]
type= 'VehicleRandStat'
func= 'setup'
pop_name='traffic_vehicles_1'
asset_file='static_traffic_vehicles.toml'
asset_sel_type='all'
asset_qty=1

[[Events.setup]]
type= 'VehicleRandStat'
func= 'setup'
pop_name='traffic_vehicles_2'
asset_file='static_traffic_vehicles.toml'
asset_sel_type='all'
asset_qty=1


#### PERIODIC EVENTS ####

[[Events.periodic.1]]
type='EgoRand'
func='randomize_position'

[[Events.periodic.1]]
type='VehicleRandStat'
func='randomize_position'
pop_name='traffic_vehicles_1'
region_type='relative_ego'
region_center='ego'
region_corners.x=[-3.0,60.0]
region_corners.y=[-4.0,-2.7]
rotation.yaw=[-5.0,5.0]
shuffle_order=true
num_placements=1
offset_type="rectangular"
ego_space=true
surface_type="all"

[[Events.periodic.1]]
type='VehicleRandStat'
func='randomize_color'
pop_name='traffic_vehicles_1'

[[Events.periodic.1]]
type='VehicleRandStat'
func='randomize_position'
pop_name='traffic_vehicles_2'
region_type='relative_entity'
region_center='traffic_vehicles_1'
region_corners.x=[-8.0,-5.5]
region_corners.y=[-0.5,0.5]
rotation.yaw=[-5.0,5.0]
shuffle_order=true
num_placements=1
offset_type="rectangular"
ego_space=true
surface_type="all"

[[Events.periodic.1]]
type='VehicleRandStat'
func='randomize_color'
pop_name='traffic_vehicles_2'

[[Events.periodic.1]]
type='PropStatic'
func='randomize_position'
pop_name='my_props'
region_type='relative_entity'
region_center='traffic_vehicles_1'
region_corners.x=[4.5,7.0]
region_corners.y=[-3.0,5.5]
rotation.yaw=[75.0,105.0]
shuffle_order=true
num_placements=1
offset_type="rectangular"
ego_space=true
surface_type="all"

# Uncomment to randomize environment.
# NOTE: Very performance heavy. Suggest every 30 frames or slower.
# Specify a range of values for each parameter to randomize.
[[Events.periodic.30]]
type='WorldRand.weather'
func='set_environment'
preset_name='random'
azimuth=[0,360]
elevation=[0,20]
cloudiness=[0.0,1.25]
fog=[0.0,0.5]
road_wetness=[0.0,1.0]
